# Generated by Django 2.0.3 on 2018-03-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoodle_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Person',
            new_name='p',
        ),
    ]
