# Generated by Django 2.0.3 on 2018-03-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoodle_app', '0002_auto_20180321_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='p',
        ),
        migrations.AddField(
            model_name='course',
            name='p',
            field=models.ManyToManyField(to='schoodle_app.Person'),
        ),
    ]
