# Generated by Django 2.0.3 on 2018-04-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoodle_app', '0003_auto_20180321_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoodle_app.Person')),
            ],
            bases=('schoodle_app.person',),
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ContentItemCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentItemList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoodle_app.ContentItem')),
            ],
        ),
        migrations.CreateModel(
            name='ContentItemFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentItem', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentPath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GradesCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradesList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoodle_app.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoodle_app.Person')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schoodle_app.ContentItemCollection')),
            ],
            bases=('schoodle_app.person',),
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoodle_app.Person')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schoodle_app.ContentItemCollection')),
                ('grades', models.ManyToManyField(to='schoodle_app.Grade')),
            ],
            bases=('schoodle_app.person',),
        ),
        migrations.RemoveField(
            model_name='course',
            name='p',
        ),
        migrations.AddField(
            model_name='person',
            name='courses',
            field=models.ManyToManyField(to='schoodle_app.Course'),
        ),
        migrations.AddField(
            model_name='coursecollection',
            name='courses',
            field=models.ManyToManyField(to='schoodle_app.Course'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='associatedCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoodle_app.Course'),
        ),
    ]
